query AppTgIntegrationPageData($appId: ID!) {
  app(appID: $appId) {
    currentUserRole
    telegramBotID
  }
}

mutation UpdateAppTelegramData($appId: ID!, $telegramBotID: Int) {
  updateApp(appID: $appId, telegramBotID: $telegramBotID) {
    telegramBotID
  }
}
