export enum PageNames {
  Main = 'main',
  UserSelection = 'user-selection',
  Apps = 'apps',
  App = 'app',
  AppGeneral = 'app-general',
  AppManagers = 'app-managers',
  AppManager = 'app-manager',
  AppManagerInvite = 'app-manager-invite',
  AppNotFound = 'app-not-found',
  AppTestGroup = 'app-test-group',
  AppTestGroups = 'app-test-groups',
  AppTg = 'app-tg',
  AppTgIntegration = 'app-tg-intergration',
  AppTgLauncher = 'app-tg-launcher',
  AppTransfer = 'app-transfer',
  AppTransferCreate = 'app-transfer-create',
  AppUrls = 'app-urls',
  AppUrlViewer = 'app-url-viewer',
  AppCache = 'app-cache',
  CreateApp = 'create-app',
  Account = 'profile',
  Privacy = 'privacy',
  TransferRequests = 'transfer-requests',
  ManagementInvites = 'management-invites',
  ManagementInvite = 'management-invite',
}
