// THIS FILE WAS AUTOGENERATED VIA SCRIPT. DO NOT EDIT.
/* eslint-disable */
export type KnownCssColorToken = (
  | 'accent-text-color'
  | 'bg-color'
  | 'black'
  | 'blue'
  | 'bottom-bar-bg-color'
  | 'brown'
  | 'button-color'
  | 'button-confirm-color'
  | 'button-destructive-color'
  | 'button-main-disabled-color'
  | 'button-text-color'
  | 'cyan'
  | 'destructive-text-color'
  | 'green'
  | 'header-bg-color'
  | 'highlight-default'
  | 'hint-color'
  | 'indigo'
  | 'link-color'
  | 'mint'
  | 'orange'
  | 'pink'
  | 'primary-fill-background'
  | 'purple'
  | 'quaternary-fill-background'
  | 'quick-menu-background'
  | 'quick-menu-foreground'
  | 'red'
  | 'secondary-accent-color'
  | 'secondary-bg-color'
  | 'secondary-fill-background'
  | 'section-bg-color'
  | 'section-header-text-color'
  | 'section-separator-color'
  | 'segmented-control-active-background'
  | 'separator-color'
  | 'separator-non-opaque'
  | 'subtitle-text-color'
  | 'teal'
  | 'tertiary-fill-background'
  | 'text-color'
  | 'text-confirm-color'
  | 'text-destructive-color'
  | 'text-main-disabled-color'
  | 'text-overlay'
  | 'toast-background'
  | 'toast-link'
  | 'tooltip-background'
  | 'tw-header-color'
  | 'white'
  | 'yellow'
);

export const knownCssColorTokensSet: Set<KnownCssColorToken> = new Set([
  'accent-text-color',
  'bg-color',
  'black',
  'blue',
  'bottom-bar-bg-color',
  'brown',
  'button-color',
  'button-confirm-color',
  'button-destructive-color',
  'button-main-disabled-color',
  'button-text-color',
  'cyan',
  'destructive-text-color',
  'green',
  'header-bg-color',
  'highlight-default',
  'hint-color',
  'indigo',
  'link-color',
  'mint',
  'orange',
  'pink',
  'primary-fill-background',
  'purple',
  'quaternary-fill-background',
  'quick-menu-background',
  'quick-menu-foreground',
  'red',
  'secondary-accent-color',
  'secondary-bg-color',
  'secondary-fill-background',
  'section-bg-color',
  'section-header-text-color',
  'section-separator-color',
  'segmented-control-active-background',
  'separator-color',
  'separator-non-opaque',
  'subtitle-text-color',
  'teal',
  'tertiary-fill-background',
  'text-color',
  'text-confirm-color',
  'text-destructive-color',
  'text-main-disabled-color',
  'text-overlay',
  'toast-background',
  'toast-link',
  'tooltip-background',
  'tw-header-color',
  'white',
  'yellow',
]);
