query AppServerlessFunctions($appId: ID!) {
  app(appID: $appId) {
    currentUserRole
    limits {
      serverlessFunctions {
        maxCount
      }
    }
    serverlessFunctions {
      id
      name
      enabled
    }
  }
}
